src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from personal.views import home_screen_view
from django.conf import settings
from django.conf.urls.static import static
from post.views import create_blog_view  
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view),
    path('blog/', create_blog_view, name='blog_posts'),  

  
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/post/urls.py
from django.urls import path
from post.views import (
    create_blog_view)

app_name= 'post'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
]

src/personal/models.py
from django.db import models

# Create your models here.

src/post/models.py
from django.db import models
from django.contrib.auth.models import User

def upload_location(instance, filename):
    file_path = 'images/{author_id}/{filename}'.format(
    author_id=str(instance.author.id),title=str(instance.title), filename=filename)

    
    return file_path

class ImagePost(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to=upload_location)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

src/post/forms.py
from django import forms

from post.models import ImagePost 


class CreateBlogPostForm(forms.ModelForm):

	class Meta:
		model = ImagePost
		fields = ['title',  'image']

src/personal/views.py
from django.shortcuts import render
from post.models import ImagePost

def home_screen_view(request):
    context = {}
    blog_posts = ImagePost.objects.all()
    context['blog_posts'] = blog_posts
    return render(request, "personal/home.html", context)

src/post/views.py
from django.shortcuts import render, redirect
from post.forms import CreateBlogPostForm
from post.models import ImagePost
def create_blog_view(request):
    context = {}
    
    if request.method == 'POST':
        form = CreateBlogPostForm(request.POST, request.FILES)
        if form.is_valid():
            author = request.user

            obj = form.save(commit=False)
            obj.author = author
            obj.save()

            form = CreateBlogPostForm()
    else:
        form = CreateBlogPostForm()

    context['form'] = form

    blog_posts = ImagePost.objects
    context['blog_posts'] = blog_posts

    return render(request, "create_image.html", context)

src/personal/templates/personal/home.html
{% extends 'base.html' %}

{% block content %}

    {% for post in image_posts %}
    
    
    {% endfor %}
{% endblock content %}

src/post/templates/create_image.html
{% extends 'base.html' %}

{% block content %}
<style type="text/css">
    .create-form {
        display: grid;
        grid-template-columns: 1fr;
        gap: 15px;
        max-width: 400px; 
        margin: auto;
        padding: 15px;
    }

    .form-group {
        display: flex;
        flex-direction: column;
    }

    .submit-button-container {
        display: flex;
        justify-content: center;
    }

    .submit-button {
        max-width: 200px;
        width: 100%; 
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}
                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
                </div>

                <div class="form-group">
                    <label for="id_body">Content</label>
                    <textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." required></textarea>
                </div>

                <div class="form-group">
                    <label for="id_image"></label>
                    <input type="file" name="image" id="id_image" accept="image/*" required>
                </div>

                <div class="submit-button-container">
                    <button class="submit-button btn btn-lg btn-primary" type="submit">POST</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>drawdrawdraw</title>

    <style>

        html{ 
            border-left: 100px solid mintcream; 
            border-right: 100px solid mintcream; 
        }

        body, h1, h4 {
            margin: 0;
            padding: 0;
        }

        body {
            background-color: lavender;
            font-family: Arial, sans-serif;
        }

        header {
            background-color: mintcream;
            color: #fff;
            text-align: center;
            padding: 20px;
        }

        header h1 {
            font-size: 36px;
            margin-bottom: 10px;
        }

        main {
            max-width: 800px;
            margin: 200px auto;
            padding: 200px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);


            
        }

        footer {
            background-color: mintcream;
            color: #fff;
            text-align: center;
            padding: 50px;
        }

        footer h4 {
            margin: 0;
        }

        h1{ 
            color: black;
        }

        .btn-create-post {
            background-color: #009688;
            color: #fff;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 5px;
            font-weight: bold;
        }

        .btn-create-post:hover {
            background-color: floralwhite;
        }

    </style>

</head>
<body>
    <header>
        <h1>Welcome to Q/A</h1>
    </header>
    <main>
        {% block content %}
        
        {% endblock content %}
    </main>
    <footer>
        <h4>
            <p class="m-auto">
                <a class="btn-create-post" href="{% url 'blog_posts' %}">Create Post</a>
            </p>
        </h4>
    </footer>
</body>
</html>